# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_InsertManualValues.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_InsertManualValues(object):
    def setupUi(self, Dialog_InsertManualValues):
        Dialog_InsertManualValues.setObjectName("Dialog_InsertManualValues")
        Dialog_InsertManualValues.resize(355, 179)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog_InsertManualValues)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_pm_10 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_pm_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_10.setObjectName("label_pm_10")
        self.gridLayout.addWidget(self.label_pm_10, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_pcErr = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_pcErr.setDecimals(4)
        self.doubleSpinBox_pcErr.setMinimum(0.001)
        self.doubleSpinBox_pcErr.setSingleStep(0.1)
        self.doubleSpinBox_pcErr.setProperty("value", 0.001)
        self.doubleSpinBox_pcErr.setObjectName("doubleSpinBox_pcErr")
        self.gridLayout.addWidget(self.doubleSpinBox_pcErr, 1, 3, 1, 1)
        self.doubleSpinBox_delta = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_delta.setDecimals(4)
        self.doubleSpinBox_delta.setMinimum(-99.0)
        self.doubleSpinBox_delta.setSingleStep(0.1)
        self.doubleSpinBox_delta.setObjectName("doubleSpinBox_delta")
        self.gridLayout.addWidget(self.doubleSpinBox_delta, 5, 1, 1, 1)
        self.doubleSpinBox_pc = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_pc.setDecimals(4)
        self.doubleSpinBox_pc.setMaximum(1.0)
        self.doubleSpinBox_pc.setSingleStep(0.1)
        self.doubleSpinBox_pc.setObjectName("doubleSpinBox_pc")
        self.gridLayout.addWidget(self.doubleSpinBox_pc, 1, 1, 1, 1)
        self.label_pm_8 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_pm_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_8.setObjectName("label_pm_8")
        self.gridLayout.addWidget(self.label_pm_8, 2, 2, 1, 1)
        self.doubleSpinBox_fcErr = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_fcErr.setDecimals(4)
        self.doubleSpinBox_fcErr.setMinimum(0.001)
        self.doubleSpinBox_fcErr.setSingleStep(0.1)
        self.doubleSpinBox_fcErr.setProperty("value", 0.001)
        self.doubleSpinBox_fcErr.setObjectName("doubleSpinBox_fcErr")
        self.gridLayout.addWidget(self.doubleSpinBox_fcErr, 2, 3, 1, 1)
        self.label_pm_11 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_pm_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_11.setObjectName("label_pm_11")
        self.gridLayout.addWidget(self.label_pm_11, 3, 2, 1, 1)
        self.doubleSpinBox_gammaErr = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_gammaErr.setDecimals(4)
        self.doubleSpinBox_gammaErr.setMinimum(0.0)
        self.doubleSpinBox_gammaErr.setSingleStep(0.1)
        self.doubleSpinBox_gammaErr.setProperty("value", 0.001)
        self.doubleSpinBox_gammaErr.setObjectName("doubleSpinBox_gammaErr")
        self.gridLayout.addWidget(self.doubleSpinBox_gammaErr, 3, 3, 1, 1)
        self.doubleSpinBox_gamma = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_gamma.setDecimals(4)
        self.doubleSpinBox_gamma.setMinimum(-99.0)
        self.doubleSpinBox_gamma.setSingleStep(0.1)
        self.doubleSpinBox_gamma.setObjectName("doubleSpinBox_gamma")
        self.gridLayout.addWidget(self.doubleSpinBox_gamma, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.doubleSpinBox_fc = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_fc.setDecimals(4)
        self.doubleSpinBox_fc.setSingleStep(0.1)
        self.doubleSpinBox_fc.setObjectName("doubleSpinBox_fc")
        self.gridLayout.addWidget(self.doubleSpinBox_fc, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog_InsertManualValues)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_InsertManualValues)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 4, 6, 1)
        self.label_6 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.doubleSpinBox_SR = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_SR.setDecimals(4)
        self.doubleSpinBox_SR.setMinimum(-99.0)
        self.doubleSpinBox_SR.setSingleStep(0.1)
        self.doubleSpinBox_SR.setObjectName("doubleSpinBox_SR")
        self.gridLayout.addWidget(self.doubleSpinBox_SR, 4, 1, 1, 1)
        self.doubleSpinBox_SRErr = QtWidgets.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_SRErr.setDecimals(4)
        self.doubleSpinBox_SRErr.setMinimum(-99.0)
        self.doubleSpinBox_SRErr.setSingleStep(0.1)
        self.doubleSpinBox_SRErr.setProperty("value", 0.001)
        self.doubleSpinBox_SRErr.setObjectName("doubleSpinBox_SRErr")
        self.gridLayout.addWidget(self.doubleSpinBox_SRErr, 4, 3, 1, 1)
        self.label_pm_12 = QtWidgets.QLabel(Dialog_InsertManualValues)
        self.label_pm_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_12.setObjectName("label_pm_12")
        self.gridLayout.addWidget(self.label_pm_12, 4, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog_InsertManualValues)
        self.buttonBox.accepted.connect(Dialog_InsertManualValues.accept)
        self.buttonBox.rejected.connect(Dialog_InsertManualValues.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_InsertManualValues)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_pc, self.doubleSpinBox_pcErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_pcErr, self.doubleSpinBox_fc)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_fc, self.doubleSpinBox_fcErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_fcErr, self.doubleSpinBox_gamma)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_gamma, self.doubleSpinBox_gammaErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_gammaErr, self.doubleSpinBox_delta)

    def retranslateUi(self, Dialog_InsertManualValues):
        _translate = QtCore.QCoreApplication.translate
        Dialog_InsertManualValues.setWindowTitle(_translate("Dialog_InsertManualValues", "Dialog"))
        self.label_pm_10.setText(_translate("Dialog_InsertManualValues", "±"))
        self.label.setText(_translate("Dialog_InsertManualValues", "Pc"))
        self.label_pm_8.setText(_translate("Dialog_InsertManualValues", "±"))
        self.label_pm_11.setText(_translate("Dialog_InsertManualValues", "±"))
        self.label_3.setText(_translate("Dialog_InsertManualValues", "Delta"))
        self.label_2.setText(_translate("Dialog_InsertManualValues", "Fc"))
        self.label_4.setText(_translate("Dialog_InsertManualValues", "γ"))
        self.label_5.setText(_translate("Dialog_InsertManualValues", "Name"))
        self.label_6.setText(_translate("Dialog_InsertManualValues", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">R</span></p></body></html>"))
        self.label_pm_12.setText(_translate("Dialog_InsertManualValues", "±"))

