# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imports/GUI_InsertManualValues.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_InsertManualValues(object):
    def setupUi(self, Dialog_InsertManualValues):
        Dialog_InsertManualValues.setObjectName(_fromUtf8("Dialog_InsertManualValues"))
        Dialog_InsertManualValues.resize(355, 179)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog_InsertManualValues)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_pm_10 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_pm_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_10.setObjectName(_fromUtf8("label_pm_10"))
        self.gridLayout.addWidget(self.label_pm_10, 1, 2, 1, 1)
        self.label = QtGui.QLabel(Dialog_InsertManualValues)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_pcErr = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_pcErr.setDecimals(4)
        self.doubleSpinBox_pcErr.setMinimum(0.001)
        self.doubleSpinBox_pcErr.setSingleStep(0.1)
        self.doubleSpinBox_pcErr.setProperty("value", 0.001)
        self.doubleSpinBox_pcErr.setObjectName(_fromUtf8("doubleSpinBox_pcErr"))
        self.gridLayout.addWidget(self.doubleSpinBox_pcErr, 1, 3, 1, 1)
        self.doubleSpinBox_delta = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_delta.setDecimals(4)
        self.doubleSpinBox_delta.setMinimum(-99.0)
        self.doubleSpinBox_delta.setSingleStep(0.1)
        self.doubleSpinBox_delta.setObjectName(_fromUtf8("doubleSpinBox_delta"))
        self.gridLayout.addWidget(self.doubleSpinBox_delta, 5, 1, 1, 1)
        self.doubleSpinBox_pc = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_pc.setDecimals(4)
        self.doubleSpinBox_pc.setMaximum(1.0)
        self.doubleSpinBox_pc.setSingleStep(0.1)
        self.doubleSpinBox_pc.setObjectName(_fromUtf8("doubleSpinBox_pc"))
        self.gridLayout.addWidget(self.doubleSpinBox_pc, 1, 1, 1, 1)
        self.label_pm_8 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_pm_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_8.setObjectName(_fromUtf8("label_pm_8"))
        self.gridLayout.addWidget(self.label_pm_8, 2, 2, 1, 1)
        self.doubleSpinBox_fcErr = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_fcErr.setDecimals(4)
        self.doubleSpinBox_fcErr.setMinimum(0.001)
        self.doubleSpinBox_fcErr.setSingleStep(0.1)
        self.doubleSpinBox_fcErr.setProperty("value", 0.001)
        self.doubleSpinBox_fcErr.setObjectName(_fromUtf8("doubleSpinBox_fcErr"))
        self.gridLayout.addWidget(self.doubleSpinBox_fcErr, 2, 3, 1, 1)
        self.label_pm_11 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_pm_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_11.setObjectName(_fromUtf8("label_pm_11"))
        self.gridLayout.addWidget(self.label_pm_11, 3, 2, 1, 1)
        self.doubleSpinBox_gammaErr = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_gammaErr.setDecimals(4)
        self.doubleSpinBox_gammaErr.setMinimum(0.0)
        self.doubleSpinBox_gammaErr.setSingleStep(0.1)
        self.doubleSpinBox_gammaErr.setProperty("value", 0.001)
        self.doubleSpinBox_gammaErr.setObjectName(_fromUtf8("doubleSpinBox_gammaErr"))
        self.gridLayout.addWidget(self.doubleSpinBox_gammaErr, 3, 3, 1, 1)
        self.doubleSpinBox_gamma = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_gamma.setDecimals(4)
        self.doubleSpinBox_gamma.setMinimum(-99.0)
        self.doubleSpinBox_gamma.setSingleStep(0.1)
        self.doubleSpinBox_gamma.setObjectName(_fromUtf8("doubleSpinBox_gamma"))
        self.gridLayout.addWidget(self.doubleSpinBox_gamma, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.doubleSpinBox_fc = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_fc.setDecimals(4)
        self.doubleSpinBox_fc.setSingleStep(0.1)
        self.doubleSpinBox_fc.setObjectName(_fromUtf8("doubleSpinBox_fc"))
        self.gridLayout.addWidget(self.doubleSpinBox_fc, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_name = QtGui.QLineEdit(Dialog_InsertManualValues)
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 3)
        self.label_5 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_InsertManualValues)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 0, 4, 6, 1)
        self.label_6 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.doubleSpinBox_SR = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_SR.setDecimals(4)
        self.doubleSpinBox_SR.setMinimum(-99.0)
        self.doubleSpinBox_SR.setSingleStep(0.1)
        self.doubleSpinBox_SR.setObjectName(_fromUtf8("doubleSpinBox_SR"))
        self.gridLayout.addWidget(self.doubleSpinBox_SR, 4, 1, 1, 1)
        self.doubleSpinBox_SRErr = QtGui.QDoubleSpinBox(Dialog_InsertManualValues)
        self.doubleSpinBox_SRErr.setDecimals(4)
        self.doubleSpinBox_SRErr.setMinimum(-99.0)
        self.doubleSpinBox_SRErr.setSingleStep(0.1)
        self.doubleSpinBox_SRErr.setProperty("value", 0.001)
        self.doubleSpinBox_SRErr.setObjectName(_fromUtf8("doubleSpinBox_SRErr"))
        self.gridLayout.addWidget(self.doubleSpinBox_SRErr, 4, 3, 1, 1)
        self.label_pm_12 = QtGui.QLabel(Dialog_InsertManualValues)
        self.label_pm_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pm_12.setObjectName(_fromUtf8("label_pm_12"))
        self.gridLayout.addWidget(self.label_pm_12, 4, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog_InsertManualValues)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_InsertManualValues.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_InsertManualValues.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_InsertManualValues)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_pc, self.doubleSpinBox_pcErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_pcErr, self.doubleSpinBox_fc)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_fc, self.doubleSpinBox_fcErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_fcErr, self.doubleSpinBox_gamma)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_gamma, self.doubleSpinBox_gammaErr)
        Dialog_InsertManualValues.setTabOrder(self.doubleSpinBox_gammaErr, self.doubleSpinBox_delta)

    def retranslateUi(self, Dialog_InsertManualValues):
        Dialog_InsertManualValues.setWindowTitle(_translate("Dialog_InsertManualValues", "Dialog", None))
        self.label_pm_10.setText(_translate("Dialog_InsertManualValues", "±", None))
        self.label.setText(_translate("Dialog_InsertManualValues", "Pc", None))
        self.label_pm_8.setText(_translate("Dialog_InsertManualValues", "±", None))
        self.label_pm_11.setText(_translate("Dialog_InsertManualValues", "±", None))
        self.label_3.setText(_translate("Dialog_InsertManualValues", "Delta", None))
        self.label_2.setText(_translate("Dialog_InsertManualValues", "Fc", None))
        self.label_4.setText(_translate("Dialog_InsertManualValues", "γ", None))
        self.label_5.setText(_translate("Dialog_InsertManualValues", "Name", None))
        self.label_6.setText(_translate("Dialog_InsertManualValues", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">R</span></p></body></html>", None))
        self.label_pm_12.setText(_translate("Dialog_InsertManualValues", "±", None))

